S3_AWS_ACCESS_KEY_ID: AKIAUZBED3ZB63Z7B77E
S3_AWS_SECRET_ACCESS_KEY: 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
TAGSAFE_RECEIVER_REDIS_URL: redis://:7eNOflYjiQ5HSjW86vooxobjfv36AXYs@redis-11872.c84.us-east-1-2.ec2.cloud.redislabs.com:11872
S3_BUCKET_NAME: development-release-monitoring-new-versions
DEFAULT_TAGSAFE_CONSUMER_JOB_QUEUE: lambda_results

MYSQL_HOST: us-east.connect.psdb.cloud
MYSQL_USER: 3fbw76z6trwgacpzjxoy
MYSQL_PASSWORD: pscale_pw_6GxJNAU1IALSMtX4lu63O9RL1Vzbs0XFiXHi84QkDVo
MYSQL_DATABASE: tagsafe