app: resque-connector
service: resque-connector
org: collin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: ${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}
    TAGSAFE_REDIS_URL: ${file(./config/${opt:stage}.yml):TAGSAFE_REDIS_URL}

functions:
  send-data:
    handler: handler.handle
    timeout: 5
    url: true

package:
  patterns:
    - '!test-data.json'

plugins:
  - serverless-offline