app: tagsafe-lambda-functions
service: html-snapshotter
org: collin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}
    CHROMIUM_EXECUTABLE: ${file(./config/${opt:stage}.yml):CHROMIUM_EXECUTABLE, ''}
    S3_AWS_ACCESS_KEY_ID: ${file(./config/${opt:stage}.yml):S3_AWS_ACCESS_KEY_ID}
    S3_AWS_SECRET_ACCESS_KEY: ${file(./config/${opt:stage}.yml):S3_AWS_SECRET_ACCESS_KEY}
    S3_BUCKET_NAME: ${file(./config/${opt:stage}.yml):S3_BUCKET_NAME}
    CONTINUE_ON_NAVIGATION_TIMEOUT: ${file(./config/${opt:stage}.yml):CONTINUE_ON_NAVIGATION_TIMEOUT, 'false'}
    NAVIGATION_TIMEOUT_MS: ${file(./config/${opt:stage}.yml):NAVIGATION_TIMEOUT_MS, '60000'}
    MOCK_S3_UPLOADS: ${file(./config/${opt:stage}.yml):MOCK_S3_UPLOADS, 'false'}

functions:
  take-snapshot:
    handler: handler.handle
    timeout: 60
    destinations:
      onSuccess: arn:aws:sqs:us-east-1:407342930315:send-development-send-results-to-tagsafe-queue
      onFailure: arn:aws:sqs:us-east-1:407342930315:send-development-send-results-to-tagsafe-queue
