name = "tagsafe-api"
main = "src/index.js"
compatibility_date = "2022-12-05"
node_compat = true

##################
###    DEV    ####
##################
[env.dev]
name = "dev-tagsafe-api"

[[env.dev.queues.producers]]
queue = "collin-dev-data-consumer"
binding = "DATA_CONSUMER_QUEUE"

[[env.dev.queues.consumers]]
queue = "collin-dev-data-consumer"
max_batch_size = 10 # optional: defaults to 10, consumer runs only once 10 messages in the queue
max_batch_timeout = 5 # optional: defaults to 5 seconds, if max_batch_size has not been met, what interval will consumer run
max_retries = 3

[env.dev.vars]
RESQUE_CONNECTOR_LAMBDA_FUNCTION_URL = "https://agtt4yi2qms6vl7zdnqlgiatzu0udzmp.lambda-url.us-east-1.on.aws/"
SENTRY_DSN = "https://12fec84d712f4dd9af3a13a6766c9867@o1079626.ingest.sentry.io/4504380124561408"

###################
### PRODUCTION ####
###################
[env.production]
name = "tagsafe-api"

[[env.production.queues.producers]]
queue = "production-data-consumer"
binding = "DATA_CONSUMER_QUEUE"

[[env.production.queues.consumers]]
queue = "production-data-consumer"
max_batch_size = 10 # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds

[env.production.vars]
RESQUE_CONNECTOR_LAMBDA_FUNCTION_URL = "https://konbotex3fn5y3nlk6aggcokue0zkzgt.lambda-url.us-east-1.on.aws/"
SENTRY_DSN = "https://12fec84d712f4dd9af3a13a6766c9867@o1079626.ingest.sentry.io/4504380124561408"
