S3_AWS_ACCESS_KEY_ID: AKIAUZBED3ZB63Z7B77E
S3_AWS_SECRET_ACCESS_KEY: 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
TAGSAFE_RECEIVER_REDIS_URL: redis://:7eNOflYjiQ5HSjW86vooxobjfv36AXYs@redis-11872.c84.us-east-1-2.ec2.cloud.redislabs.com:11872
S3_BUCKET_NAME: development-release-monitoring-new-versions
DEFAULT_TAGSAFE_CONSUMER_JOB_QUEUE: lambda_results

MYSQL_HOST: uktps5iumngsxem7.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
MYSQL_USER: m2hrx16nzgeir2q8
MYSQL_PASSWORD: oyremq45h4t5mic9
MYSQL_DATABASE: primary_app_db