one_minute_check_scripts:
  class: Schedule::OneMinuteTagCheckerJob
  cron: "*/1 * * * *" # every 1 minute
  description: "Checks all scripts to check if they've been changed."
  queue: "clean_data_queue"
re_scan_domains:
  class: Schedule::ScanDomainsJob
  cron: "0 */1 * * *" # every 1 hour
  description: "Scans each domain for any new third party tags."
  queue: "scan_domain_queue"
fail_stale_pending_audits:
  class: Schedule::FailStalePendingAuditsJob
  cron: "0 */1 * * *" # every 1 hour
  description: "Fails any audits that are stuck in pending."
  queue: "default"
clean_out_retention_data:
  class: Schedule::CleanOutOfRetentionDataJob
  cron: "0 */1 * * *" # every 1 hour
  queue: "clean_data_queue"