re_enqueue_failed_jobs:
  class: Schedule::ReEnqueueFailedJobs
  cron: "*/1 * * * *" # every 1 minute
  queue: critical # probably not the right queue but it needs to be in a queue with low volume, this job should be very quick
  description: "Checks the Failed Resque queue for jobs that failed with `DirtyExits` and re-enqueues them."
clean_out_retention_data:
  class: Schedule::CleanOutOfRetentionDataJob
  cron: "0 0 * * *" # every night at midnight
  queue: normal