clean_out_retention_data:
  class: Schedule::ReEnqueueFailedJobs
  cron: "*/1 * * * *" # every 1 minute
  queue: "default_queue"
one_minute_check_scripts:
  class: Schedule::TagCheckJobs::OneMinuteInterval
  cron: "*/1 * * * *" # every 1 minute
  description: "Checks all tags set for 1 minute intervals to evalute if there's a new version."
  queue: "tag_checker_queue"
re_scan_domains:
  class: Schedule::CrawlUrlsJob
  cron: "0 */1 * * *" # every 1 hour
  description: "Scans each domain for any new third party tags."
  # queue: "crawl_url_for_tags_queue"
  queue: "default_queue"
clean_out_retention_data:
  class: Schedule::CleanOutOfRetentionDataJob
  cron: "0 0 * * *" # every night at midnight
  queue: "default_queue"