one_minute_check_scripts:
  class: Schedule::TagCheckJobs::OneMinuteInterval
  cron: "*/1 * * * *" # every 1 minute
  description: "Checks all tags set for 1 minute intervals to evalute if there's a new version."
  queue: "tag_checker_queue"
re_scan_domains:
  class: Schedule::CrawlUrlsJob
  cron: "0 */1 * * *" # every 1 hour
  description: "Scans each domain for any new third party tags."
  queue: "scan_domain_queue"
fail_stale_pending_audits:
  class: Schedule::FailStaleLambdaFunctionsJob
  cron: "0 */1 * * *" # every 1 hour
  description: "Fails any audits or URL crawls that are stuck in pending."
  queue: "default"
clean_out_retention_data:
  class: Schedule::CleanOutOfRetentionDataJob
  cron: "0 */1 * * *" # every 1 hour
  queue: "clean_data_queue"