one_minute_check_scripts:
  class: OneMinuteScriptCheckerJob
  cron: "*/1 * * * *" # every 1 minute
  description: "Checks all scripts to check if they've been changed."
  queue: "default"
re_scan_domains:
  class: ScanDomainsJob
  cron: "0 */1 * * *" # every 1 hour
  description: "Scans each domain for any new third party tags."
  queue: "default"
re_scan_domains:
  class: FailStalePendingAuditsJob
  cron: "0 */1 * * *" # every 1 hour
  description: "Fails any audits that are stuck in pending."
  queue: "default"