default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  username: root
  password: password
  host: localhost
  database: tagsafe_test

development:
  <<: *default
  database: tagsafe_development
  username: admin
  password: waunyh2hvd_tym1EGH
  host: collin-dev-db.cytsjoeoway1.us-east-1.rds.amazonaws.com
  port: 3306

staging:
  <<: *default
  database: tagsafe_staging
  username: admin
  password: jpk-wqz!HRX7ugt0cnz
  host: tagsafe-staging.cytsjoeoway1.us-east-1.rds.amazonaws.com
  port: 3306

production:
  <<: *default
  database: tagsafe_production
  username: admin
  password: DCR6qyd8muj*ezq4pek
  host: tagsafe-production.cytsjoeoway1.us-east-1.rds.amazonaws.com
  password: 3306