default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

pscale_collin_dev: &pscale_collin_dev
  <<: *default
  database: tagsafe-production
  username: 5brtvts8zxz7
  host: pds4kx1y2m0n.us-east-4.psdb.cloud
  password: pscale_pw_6NepzsiSIxbvVLhdkc868dEgFcqrsf0BISwCPuUInkM
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

local: &local
  <<: *default
  database: tagsafe_development
  username: root
  password: password
  host: localhost

test:
  <<: *local
  database: tagsafe_test

development:
  <<: *pscale_collin_dev

staging:
  <<: *default
  database: tagsafe-production
  username: 8otvu8ilamwq
  host: zndnr0yzsrhi.us-east-2.psdb.cloud
  password: pscale_pw_oUBt1ZNscnlUfR_SXb34sSaFFUWyWcenNHLR5Xuf2wY

production:
  <<: *default
  database: tagsafe-production
  username: bqmc4lhu2ms9
  host: vtc9xo21h5ce.us-east-4.psdb.cloud
  password: pscale_pw_bU3z9t9Y9sq1g4ncMOJpWOkGOitpQGSphA2WMoXwRzA