default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

pscale_collin_dev: &pscale_collin_dev
  <<: *default
  database: tagsafe-production
  username: 5brtvts8zxz7
  host: pds4kx1y2m0n.us-east-4.psdb.cloud
  password: pscale_pw_6NepzsiSIxbvVLhdkc868dEgFcqrsf0BISwCPuUInkM
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

pscale_alert_updates: &pscale_alert_updates
  <<: *default
  database: tagsafe-production
  username: th6mlmwbe2vi
  host: yyb5pgooicdr.us-east-3.psdb.cloud
  password: pscale_pw_BbdKSiWnyXISF0xrn-6mdSJZJG9oyxajoHwirfTjK14
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"


local: &local
  <<: *default
  database: tagsafe_development
  username: root
  password: password
  host: localhost

test:
  <<: *local
  database: tagsafe_test

development:
  <<: *pscale_collin_dev

staging:
  <<: *default
  database: tagsafe_staging
  username: admin
  password: jpk-wqz!HRX7ugt0cnz
  host: tagsafe-staging.cytsjoeoway1.us-east-1.rds.amazonaws.com
  port: 3306

production:
  <<: *default
  database: tagsafe_production
  username: admin
  password: DCR6qyd8muj*ezq4pek
  host: tagsafe-production.cytsjoeoway1.us-east-1.rds.amazonaws.com
  password: 3306