default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: tag_safe_development

  # PLANET SCALE, DOESNT LIKE FOREIGN KEYS?
  # database: tagsafe-dev
  # username: hpsjx9vnwl7l
  # host: 5wpdev0dcvl8.us-east-1.psdb.cloud
  # password: pscale_pw_m0MgUs18hyJriKsbBaVEnA6dpkozxEooC4wfOfRCDK0

test:
  <<: *default
  database: tag_safe_test

production:
  <<: *default
  database: tag_safe_production
  username: tag_safe
  password: <%= ENV['TAG_SAFE_DATABASE_PASSWORD'] %>