default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password: password
  # host: localhost

development:
  <<: *default
  # database: tag_safe_development
  host: ble5mmo2o5v9oouq.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
  username: liumxww8qzltxgf4
  password: btxo1zn78wy2uqyd
  database: q2mn5mg2xvmqq5fk

test:
  <<: *default
  database: tag_safe_test

staging:
  <<: *default
  url: <%= ENV['JAWSDB_URL'] %>

production:
  <<: *default
  database: tag_safe_production
  username: tag_safe
  password: <%= ENV['TAG_SAFE_DATABASE_PASSWORD'] %>