default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # database: tag_safe_development
  url: mysql2://liumxww8qzltxgf4:btxo1zn78wy2uqyd@ble5mmo2o5v9oouq.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/q2mn5mg2xvmqq5fk

test:
  <<: *default
  username: root
  password: password
  host: localhost
  database: tag_safe_test

staging:
  <<: *default
  url: <%= ENV['JAWSDB_URL'] %>

production:
  <<: *default
  database: tag_safe_production
  username: tag_safe
  password: <%= ENV['TAG_SAFE_DATABASE_PASSWORD'] %>