default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  username: root
  password: password
  host: localhost
  database: tagsafe_test

development:
  <<: *default
  database: collin-dev
  username: babluh3ifjpm
  host: 86o6ha6kvuuj.us-east-1.psdb.cloud
  password: pscale_pw_KxY0fuC36ypQW5IcmLPPq4kUAnXPXJQXf9gtBNEPBlM
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

staging:
  <<: *default
  database: tagsafe-staging
  username: xss7b92kzyyo
  host: gmy4rjpsfwqz.us-east-4.psdb.cloud
  password: pscale_pw_GGUqasfU0Az1wVKJ2_nJROA-EKE0oiB-FO6PWsI5hlU

production:
  <<: *default
  database: tagsafe-production
  username: bqmc4lhu2ms9
  host: vtc9xo21h5ce.us-east-4.psdb.cloud
  password: pscale_pw_bU3z9t9Y9sq1g4ncMOJpWOkGOitpQGSphA2WMoXwRzA