default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

pscale_collin_dev: &pscale_collin_dev
  <<: *default
  adapter: mysql2
  database: tagsafe-app
  username: m9rqiucjoxt1n7ifq2jr
  host: us-east.connect.psdb.cloud
  password: pscale_pw_1TnSNykRYawjNmjrJY718HelwrVM573a9wyWKJDYz4I
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

local: &local
  <<: *default
  database: tagsafe_development
  username: root
  password: password
  host: localhost

re_architect: &re_architect
  <<: *default
  adapter: mysql2
  database: tagsafe-app
  username: v4kxfo7lg621lf4cdnnq
  host: us-east.connect.psdb.cloud
  password: pscale_pw_OpgsZ045sPRK2r32xahFYYIVd7k13Z9kVqOzCKO27WH
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

test:
  <<: *local
  database: tagsafe_test

# development:
#   <<: *pscale_collin_dev

development:
  <<: *default
  adapter: mysql2
  database: tagsafe
  username: vo3mcbuid2u4alzivjqe
  host: us-east.connect.psdb.cloud
  password: pscale_pw_xH5dKq9EAcgQNTCbf46oXZoYXyXsZUt84phhhWEUEei
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"


# staging:
#   <<: *default

production:
  <<: *default
  adapter: mysql2
  database: tagsafe
  username: vo3mcbuid2u4alzivjqe
  host: us-east.connect.psdb.cloud
  password: pscale_pw_xH5dKq9EAcgQNTCbf46oXZoYXyXsZUt84phhhWEUEei
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

