default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

aws_rds_collin_dev: &aws_rds
  url: mysql2://root:MCD9kty.vkb!ybx9haq@tagsafe-collin-local-development.cytsjoeoway1.us-east-1.rds.amazonaws.com:3306/tagsafe_collin_dev

jaws_db_collin_dev: &jaws_db_collin_dev
  # OLD url: mysql2://liumxww8qzltxgf4:btxo1zn78wy2uqyd@ble5mmo2o5v9oouq.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/q2mn5mg2xvmqq5fk
  url: mysql2://m2hrx16nzgeir2q8:oyremq45h4t5mic9@uktps5iumngsxem7.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/primary_app_db


# local_db: &local_db
#   username: root
#   # password: password
#   host: localhost
#   database: tagsafe_development

development:
  <<: *default
  <<: *jaws_db_collin_dev

test:
  <<: *default
  username: root
  password: password
  host: localhost
  database: tag_safe_test

staging:
  <<: *default
  url: <%= ENV['JAWSDB_URL'] %>

production:
  <<: *default
  database: tag_safe_production
  username: tag_safe
  password: <%= ENV['TAG_SAFE_DATABASE_PASSWORD'] %>