default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

pscale_collin_dev: &pscale_collin_dev
  <<: *default
  adapter: mysql2
  database: tagsafe-app
  username: m9rqiucjoxt1n7ifq2jr
  host: us-east.connect.psdb.cloud
  password: pscale_pw_1TnSNykRYawjNmjrJY718HelwrVM573a9wyWKJDYz4I
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

local: &local
  <<: *default
  database: tagsafe_development
  username: root
  password: password
  host: localhost

test:
  <<: *local
  database: tagsafe_test

development:
  <<: *pscale_collin_dev

# staging:
#   <<: *default

production:
  <<: *default
  database: tagsafe-app
  username: 1t7vj3ce3zcbbb9yjk2l
  host: us-east.connect.psdb.cloud
  password: pscale_pw_WK2LdE5yjgRjsJ6Pa7EykSY28naR9Zd0GZOu2hNcYKq
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"
