tag_version_s3:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-east-1
  bucket: tagsafe-<%= Rails.env %>-tag-versions
  public: true # important - sets S3 objects to be publicly available, needed for Cloudfront

tag_image_s3:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-east-1
  bucket: tagsafe-<%= Rails.env %>-tag-images
  public: true # important - sets S3 objects to be publicly available, needed for Cloudfront

tag_js_script_s3:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-east-1
  bucket: tagsafe-<%= Rails.env %>-tag-js-scripts
  public: true # important - sets S3 objects to be publicly available, needed for Cloudfront

# why does rspec throw an error when this isnt present....
test:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-east-1
  bucket: test-bucket-should-never-exist