CHROMIUM_EXECUTABLE: /Users/collin/.npm-global/bin/chrome
NODE_ENV: local
S3_BUCKET_NAME: html-snapshotter-files-development
S3_AWS_ACCESS_KEY_ID: AKIAV5V4H3GFRTGOCY52
S3_AWS_SECRET_ACCESS_KEY: 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
NAVIGATION_TIMEOUT_MS: 60000
CONTINUE_ON_NAVIGATION_TIMEOUT: 'true'
MOCK_S3_UPLOADS: 'true'