TAGSAFE_RECEIVER_REDIS_URL: redis://:7eNOflYjiQ5HSjW86vooxobjfv36AXYs@redis-11872.c84.us-east-1-2.ec2.cloud.redislabs.com:11872
S3_BUCKET_NAME: development-release-monitoring-new-versions
DEFAULT_TAGSAFE_CONSUMER_JOB_QUEUE: lambda_results
S3_AWS_ACCESS_KEY_ID: AKIAUZBED3ZB63Z7B77E
S3_AWS_SECRET_ACCESS_KEY: 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

MYSQL_HOST: collin-dev-db.cytsjoeoway1.us-east-1.rds.amazonaws.com
MYSQL_USER: admin
MYSQL_PASSWORD: waunyh2hvd_tym1EGH
MYSQL_DATABASE: tagsafe_development