S3_AWS_ACCESS_KEY_ID: AKIAUZBED3ZB63Z7B77E
S3_AWS_SECRET_ACCESS_KEY: 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
TAGSAFE_RECEIVER_REDIS_URL: redis://:7eNOflYjiQ5HSjW86vooxobjfv36AXYs@redis-11872.c84.us-east-1-2.ec2.cloud.redislabs.com:11872
S3_BUCKET_NAME: development-release-monitoring-new-versions
DEFAULT_TAGSAFE_CONSUMER_JOB_QUEUE: lambda_results

# credit_wallet_enhancements branch
MYSQL_HOST: drqkxa8s3yue.us-east-2.psdb.cloud
MYSQL_USER: 07kxbkkpokum
MYSQL_PASSWORD: pscale_pw_PHeXFv57CGlSF0U9_BgJf5vPdfLiB7u-JducTw4L3Ao
MYSQL_DATABASE: tagsafe-production