TAGSAFE_RECEIVER_REDIS_URL: redis://:LrA3FWb1tpZItA94C9m6X8JnVUus48Yy@redis-11898.c16.us-east-1-3.ec2.cloud.redislabs.com:11898
S3_BUCKET_NAME: production-release-monitoring-new-versions
DEFAULT_TAGSAFE_CONSUMER_JOB_QUEUE: lambda_results
S3_AWS_ACCESS_KEY_ID: AKIAV5V4H3GFRTGOCY52
S3_AWS_SECRET_ACCESS_KEY: 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

MYSQL_DATABASE: tagsafe-production
MYSQL_USER: bqmc4lhu2ms9
MYSQL_HOST: vtc9xo21h5ce.us-east-4.psdb.cloud
MYSQL_PASSWORD: pscale_pw_bU3z9t9Y9sq1g4ncMOJpWOkGOitpQGSphA2WMoXwRzA