app: crawler
service: url-crawler
org: collin

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: ${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}
    CHROMIUM_EXECUTABLE: ${file(./config/${opt:stage}.yml):CHROMIUM_EXECUTABLE, ''}
    CONSIDER_SUB_DOMAINS_FIRST_PARTY: ${file(./config/${opt:stage}.yml):CONSIDER_SUB_DOMAINS_FIRST_PARTY, ''}
    S3_AWS_ACCESS_KEY_ID: ${file(./config/${opt:stage}.yml):S3_AWS_ACCESS_KEY_ID}
    S3_AWS_SECRET_ACCESS_KEY: ${file(./config/${opt:stage}.yml):S3_AWS_SECRET_ACCESS_KEY}

functions:
  find-third-party-tags:
    handler: handler.handle
    timeout: 90

package:
  patterns:
    - '!node_modules/puppeteer/.local-chromium/**'
    - '!tests/**'

plugins:
  - serverless-offline