app: unique-num-hosts-counter
service: count-unique-hosts
org: collin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: ${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}

functions:
  count-hosts:
    handler: handler.handle
    timeout: 90

package:
  patterns:
    - '!node_modules/puppeteer/.local-chromium/**'