const PuppeteerModerator = require("./src/puppeteerModerator");
const fs = require('fs');

module.exports.scrapeBookface = async (event, _context) => {
  const bookfaceUrls = [
    "https://bookface.ycombinator.com/company/28080",
    "https://bookface.ycombinator.com/company/27925",
    "https://bookface.ycombinator.com/company/28364",
    "https://bookface.ycombinator.com/company/28162",
    "https://bookface.ycombinator.com/company/28421",
    "https://bookface.ycombinator.com/company/27923",
    "https://bookface.ycombinator.com/company/28071",
    "https://bookface.ycombinator.com/company/27922",
    "https://bookface.ycombinator.com/company/28127",
    "https://bookface.ycombinator.com/company/27834",
    "https://bookface.ycombinator.com/company/27862",
    "https://bookface.ycombinator.com/company/28118",
    "https://bookface.ycombinator.com/company/27893",
    "https://bookface.ycombinator.com/company/27762",
    "https://bookface.ycombinator.com/company/27676",
    "https://bookface.ycombinator.com/company/28070",
    "https://bookface.ycombinator.com/company/28013",
    "https://bookface.ycombinator.com/company/28409",
    "https://bookface.ycombinator.com/company/27853",
    "https://bookface.ycombinator.com/company/28093",
    "https://bookface.ycombinator.com/company/27825",
    "https://bookface.ycombinator.com/company/27926",
    "https://bookface.ycombinator.com/company/27763",
    "https://bookface.ycombinator.com/company/27678",
    "https://bookface.ycombinator.com/company/27883",
    "https://bookface.ycombinator.com/company/27812",
    "https://bookface.ycombinator.com/company/27946",
    "https://bookface.ycombinator.com/company/28363",
    "https://bookface.ycombinator.com/company/27899",
    "https://bookface.ycombinator.com/company/28141",
    "https://bookface.ycombinator.com/company/27956",
    "https://bookface.ycombinator.com/company/26837",
    "https://bookface.ycombinator.com/company/28218",
    "https://bookface.ycombinator.com/company/27669",
    "https://bookface.ycombinator.com/company/27700",
    "https://bookface.ycombinator.com/company/27675",
    "https://bookface.ycombinator.com/company/28129",
    "https://bookface.ycombinator.com/company/28303",
    "https://bookface.ycombinator.com/company/28183",
    "https://bookface.ycombinator.com/company/27961",
    "https://bookface.ycombinator.com/company/27774",
    "https://bookface.ycombinator.com/company/28048",
    "https://bookface.ycombinator.com/company/27814",
    "https://bookface.ycombinator.com/company/27831",
    "https://bookface.ycombinator.com/company/27813",
    "https://bookface.ycombinator.com/company/27674",
    "https://bookface.ycombinator.com/company/27924",
    "https://bookface.ycombinator.com/company/27754",
    "https://bookface.ycombinator.com/company/28074",
    "https://bookface.ycombinator.com/company/28440",
    "https://bookface.ycombinator.com/company/28045",
    "https://bookface.ycombinator.com/company/28410",
    "https://bookface.ycombinator.com/company/27673",
    "https://bookface.ycombinator.com/company/28008",
    "https://bookface.ycombinator.com/company/27960",
    "https://bookface.ycombinator.com/company/27583",
    "https://bookface.ycombinator.com/company/27878",
    "https://bookface.ycombinator.com/company/28221",
    "https://bookface.ycombinator.com/company/28082",
    "https://bookface.ycombinator.com/company/27907",
    "https://bookface.ycombinator.com/company/28075",
    "https://bookface.ycombinator.com/company/27707",
    "https://bookface.ycombinator.com/company/27680",
    "https://bookface.ycombinator.com/company/27832",
    "https://bookface.ycombinator.com/company/28329",
    "https://bookface.ycombinator.com/company/28418",
    "https://bookface.ycombinator.com/company/28301",
    "https://bookface.ycombinator.com/company/27942",
    "https://bookface.ycombinator.com/company/28417",
    "https://bookface.ycombinator.com/company/27838",
    "https://bookface.ycombinator.com/company/28158",
    "https://bookface.ycombinator.com/company/27968",
    "https://bookface.ycombinator.com/company/28111",
    "https://bookface.ycombinator.com/company/27668",
    "https://bookface.ycombinator.com/company/27927",
    "https://bookface.ycombinator.com/company/27839",
    "https://bookface.ycombinator.com/company/27841",
    "https://bookface.ycombinator.com/company/27829",
    "https://bookface.ycombinator.com/company/27254",
    "https://bookface.ycombinator.com/company/27713",
    "https://bookface.ycombinator.com/company/27699",
    "https://bookface.ycombinator.com/company/28110",
    "https://bookface.ycombinator.com/company/28081",
    "https://bookface.ycombinator.com/company/27972",
    "https://bookface.ycombinator.com/company/27693",
    "https://bookface.ycombinator.com/company/28037",
    "https://bookface.ycombinator.com/company/27686",
    "https://bookface.ycombinator.com/company/28128",
    "https://bookface.ycombinator.com/company/28216",
    "https://bookface.ycombinator.com/company/28119",
    "https://bookface.ycombinator.com/company/28160",
    "https://bookface.ycombinator.com/company/28432",
    "https://bookface.ycombinator.com/company/27852",
    "https://bookface.ycombinator.com/company/27766",
    "https://bookface.ycombinator.com/company/27818",
    "https://bookface.ycombinator.com/company/27882",
    "https://bookface.ycombinator.com/company/27951",
    "https://bookface.ycombinator.com/company/27881",
    "https://bookface.ycombinator.com/company/28159",
    "https://bookface.ycombinator.com/company/28079",
    "https://bookface.ycombinator.com/company/27817",
    "https://bookface.ycombinator.com/company/27858",
    "https://bookface.ycombinator.com/company/28192",
    "https://bookface.ycombinator.com/company/27820",
    "https://bookface.ycombinator.com/company/27201",
    "https://bookface.ycombinator.com/company/27666",
    "https://bookface.ycombinator.com/company/28205",
    "https://bookface.ycombinator.com/company/28415",
    "https://bookface.ycombinator.com/company/27728",
    "https://bookface.ycombinator.com/company/27705",
    "https://bookface.ycombinator.com/company/27815",
    "https://bookface.ycombinator.com/company/27985",
    "https://bookface.ycombinator.com/company/27816",
    "https://bookface.ycombinator.com/company/27901",
    "https://bookface.ycombinator.com/company/28425",
    "https://bookface.ycombinator.com/company/27694",
    "https://bookface.ycombinator.com/company/28112",
    "https://bookface.ycombinator.com/company/27785",
    "https://bookface.ycombinator.com/company/27880",
    "https://bookface.ycombinator.com/company/27928",
    "https://bookface.ycombinator.com/company/27702",
    "https://bookface.ycombinator.com/company/27692",
    "https://bookface.ycombinator.com/company/27734",
    "https://bookface.ycombinator.com/company/27828",
    "https://bookface.ycombinator.com/company/27987",
    "https://bookface.ycombinator.com/company/27950",
    "https://bookface.ycombinator.com/company/27949",
    "https://bookface.ycombinator.com/company/27667",
    "https://bookface.ycombinator.com/company/27919",
    "https://bookface.ycombinator.com/company/27902",
    "https://bookface.ycombinator.com/company/28089",
    "https://bookface.ycombinator.com/company/27826",
    "https://bookface.ycombinator.com/company/28078",
    "https://bookface.ycombinator.com/company/27701",
    "https://bookface.ycombinator.com/company/28416",
    "https://bookface.ycombinator.com/company/28131",
    "https://bookface.ycombinator.com/company/27969",
    "https://bookface.ycombinator.com/company/27959",
    "https://bookface.ycombinator.com/company/28088",
    "https://bookface.ycombinator.com/company/27890",
    "https://bookface.ycombinator.com/company/27867",
    "https://bookface.ycombinator.com/company/27655",
    "https://bookface.ycombinator.com/company/28091",
    "https://bookface.ycombinator.com/company/27845",
    "https://bookface.ycombinator.com/company/27894",
    "https://bookface.ycombinator.com/company/27952",
    "https://bookface.ycombinator.com/company/27684",
    "https://bookface.ycombinator.com/company/27842",
    "https://bookface.ycombinator.com/company/27844",
    "https://bookface.ycombinator.com/company/28108",
    "https://bookface.ycombinator.com/company/28361",
    "https://bookface.ycombinator.com/company/27690",
    "https://bookface.ycombinator.com/company/27871",
    "https://bookface.ycombinator.com/company/27939",
    "https://bookface.ycombinator.com/company/27982",
    "https://bookface.ycombinator.com/company/28092",
    "https://bookface.ycombinator.com/company/27860",
    "https://bookface.ycombinator.com/company/28103",
    "https://bookface.ycombinator.com/company/27936",
    "https://bookface.ycombinator.com/company/27704",
    "https://bookface.ycombinator.com/company/27819",
    "https://bookface.ycombinator.com/company/27873",
    "https://bookface.ycombinator.com/company/27898",
    "https://bookface.ycombinator.com/company/27964",
    "https://bookface.ycombinator.com/company/27938",
    "https://bookface.ycombinator.com/company/27911",
    "https://bookface.ycombinator.com/company/27875",
    "https://bookface.ycombinator.com/company/28019",
    "https://bookface.ycombinator.com/company/27840",
    "https://bookface.ycombinator.com/company/27897",
    "https://bookface.ycombinator.com/company/28113",
    "https://bookface.ycombinator.com/company/28094",
    "https://bookface.ycombinator.com/company/28090",
    "https://bookface.ycombinator.com/company/27697",
    "https://bookface.ycombinator.com/company/27843",
    "https://bookface.ycombinator.com/company/27989",
    "https://bookface.ycombinator.com/company/28006",
    "https://bookface.ycombinator.com/company/28096",
    "https://bookface.ycombinator.com/company/27740",
    "https://bookface.ycombinator.com/company/27983",
    "https://bookface.ycombinator.com/company/28007",
    "https://bookface.ycombinator.com/company/27691",
    "https://bookface.ycombinator.com/company/27424",
    "https://bookface.ycombinator.com/company/27941",
    "https://bookface.ycombinator.com/company/27868",
    "https://bookface.ycombinator.com/company/27714",
    "https://bookface.ycombinator.com/company/28175",
    "https://bookface.ycombinator.com/company/27695",
    "https://bookface.ycombinator.com/company/27837",
    "https://bookface.ycombinator.com/company/27846",
    "https://bookface.ycombinator.com/company/27821",
    "https://bookface.ycombinator.com/company/27876",
    "https://bookface.ycombinator.com/company/27943",
    "https://bookface.ycombinator.com/company/27836",
    "https://bookface.ycombinator.com/company/27687",
    "https://bookface.ycombinator.com/company/27696",
    "https://bookface.ycombinator.com/company/27703",
    "https://bookface.ycombinator.com/company/28018",
    "https://bookface.ycombinator.com/company/27892",
    "https://bookface.ycombinator.com/company/27984",
    "https://bookface.ycombinator.com/company/27874",
    "https://bookface.ycombinator.com/company/28107",
    "https://bookface.ycombinator.com/company/28080",
    "https://bookface.ycombinator.com/company/27967",
    "https://bookface.ycombinator.com/company/28180",
    "https://bookface.ycombinator.com/company/27986",
    "https://bookface.ycombinator.com/company/27896",
    "https://bookface.ycombinator.com/company/27966",
    "https://bookface.ycombinator.com/company/28178",
    "https://bookface.ycombinator.com/company/27683",
    "https://bookface.ycombinator.com/company/27698",
    "https://bookface.ycombinator.com/company/28115",
    "https://bookface.ycombinator.com/company/28116",
    "https://bookface.ycombinator.com/company/27869",
    "https://bookface.ycombinator.com/company/27822",
    "https://bookface.ycombinator.com/company/27850",
    "https://bookface.ycombinator.com/company/27906",
    "https://bookface.ycombinator.com/company/27971",
    "https://bookface.ycombinator.com/company/28367",
    "https://bookface.ycombinator.com/company/28114",
    "https://bookface.ycombinator.com/company/27672",
    "https://bookface.ycombinator.com/company/27810",
    "https://bookface.ycombinator.com/company/28371",
    "https://bookface.ycombinator.com/company/27859",
    "https://bookface.ycombinator.com/company/27712",
    "https://bookface.ycombinator.com/company/27855",
    "https://bookface.ycombinator.com/company/27857",
    "https://bookface.ycombinator.com/company/27824",
    "https://bookface.ycombinator.com/company/28077",
    "https://bookface.ycombinator.com/company/28097",
    "https://bookface.ycombinator.com/company/27685",
    "https://bookface.ycombinator.com/company/27935",
    "https://bookface.ycombinator.com/company/27991",
    "https://bookface.ycombinator.com/company/27809",
    "https://bookface.ycombinator.com/company/27914",
    "https://bookface.ycombinator.com/company/27811",
    "https://bookface.ycombinator.com/company/27708",
    "https://bookface.ycombinator.com/company/27870",
    "https://bookface.ycombinator.com/company/27710",
    "https://bookface.ycombinator.com/company/27711",
    "https://bookface.ycombinator.com/company/28072",
    "https://bookface.ycombinator.com/company/27921",
    "https://bookface.ycombinator.com/company/27974",
    "https://bookface.ycombinator.com/company/27957",
    "https://bookface.ycombinator.com/company/27664",
    "https://bookface.ycombinator.com/company/28366",
    "https://bookface.ycombinator.com/company/28214",
    "https://bookface.ycombinator.com/company/27965",
    "https://bookface.ycombinator.com/company/27953",
    "https://bookface.ycombinator.com/company/27947",
    "https://bookface.ycombinator.com/company/28414",
    "https://bookface.ycombinator.com/company/27677",
    "https://bookface.ycombinator.com/company/28099",
    "https://bookface.ycombinator.com/company/27671",
    "https://bookface.ycombinator.com/company/27879",
    "https://bookface.ycombinator.com/company/27945",
    "https://bookface.ycombinator.com/company/27670",
    "https://bookface.ycombinator.com/company/27958",
    "https://bookface.ycombinator.com/company/27492",
    "https://bookface.ycombinator.com/company/27735",
    "https://bookface.ycombinator.com/company/27823",
    "https://bookface.ycombinator.com/company/27725",
    "https://bookface.ycombinator.com/company/28073",
    "https://bookface.ycombinator.com/company/27992",
    "https://bookface.ycombinator.com/company/28069",
    "https://bookface.ycombinator.com/company/27978",
    "https://bookface.ycombinator.com/company/27915",
    "https://bookface.ycombinator.com/company/28098",
    "https://bookface.ycombinator.com/company/27679",
    "https://bookface.ycombinator.com/company/28087",
    "https://bookface.ycombinator.com/company/27806",
    "https://bookface.ycombinator.com/company/27808",
    "https://bookface.ycombinator.com/company/27491",
    "https://bookface.ycombinator.com/company/27909",
    "https://bookface.ycombinator.com/company/28368",
    "https://bookface.ycombinator.com/company/28413",
    "https://bookface.ycombinator.com/company/28412",
    "https://bookface.ycombinator.com/company/26884",
    "https://bookface.ycombinator.com/company/27854",
    "https://bookface.ycombinator.com/company/28370",
    "https://bookface.ycombinator.com/company/27877",
    "https://bookface.ycombinator.com/company/28448",
    "https://bookface.ycombinator.com/company/28382",
    "https://bookface.ycombinator.com/company/28372",
    "https://bookface.ycombinator.com/company/27827",
    "https://bookface.ycombinator.com/company/28369",
    "https://bookface.ycombinator.com/company/27807"
  ];
  const puppeteerModerator = new PuppeteerModerator();
  const page = await puppeteerModerator.launch();

  console.log('Going to YC website...');
  await page.goto('https://account.ycombinator.com', { waituntil: 'domcontentloaded' });
  console.log('Logging in.....');
  await page.type('#ycid-input', 'collinschneider');
  await page.type('#password-input', 'Thomas34?');
  console.log('Submitting.....');
  await Promise.all([
    page.waitForNavigation(),
    page.click('button[type="submit"]'),
  ]);

  const results = {};
  for(let i = 0; i < bookfaceUrls.length; i++) {
    try {
      await getCompanyDetailsFromBookfaceUrl(bookfaceUrls[i], page, results);
    } catch(err) {
      console.log(`Error on ${bookfaceUrls[i]}: ${err}`);
    }
  }
  console.log(results);
  fs.writeFileSync('results.json', JSON.stringify(results));
  return companyUrls;
}

function onlyUnique(value, index, self) {
  return self.indexOf(value) === index;
}

async function getCompanyDetailsFromBookfaceUrl(bookfaceUrl, page, resultsHash) {
  await page.goto(bookfaceUrl, { waituntil: 'domcontentloaded' });
  const companyUrlSelectors = 'div[id^=ShowCompany-react] a[href][target]';
  const companyUrls = await page.$$eval(companyUrlSelectors, (els) => Array.from(els).map(el => el.href));
  const uniqueCompanyUrls = companyUrls.filter(onlyUnique);
  for(let i = 0; i < uniqueCompanyUrls.length; i++) {
    const thirdPartyTags = await getThirdPartyTagsFromUrl(uniqueCompanyUrls[i], page);
    resultsHash[uniqueCompanyUrls[i]] = {
      url: uniqueCompanyUrls[i],
      bookfaceUrl,
      thirdPartyTags
    };
  }
}

async function getThirdPartyTagsFromUrl(url, page) {
  await page.goto(url, { waituntil: 'domcontentloaded' });
  const thirdPartyTagSelectors = 'script[src^="http"]';
  const scripts = await page.$$eval(thirdPartyTagSelectors, (els) => Array.from(els).map(el => el.src));
  const pageHost = new URL(url).host;
  const thirdPartyScripts = scripts.filter(script => {
    const scriptHost = new URL(script).host;
    return scriptHost !== pageHost;
  });
  return thirdPartyScripts;
}