app: bookface-scraper
service: scrape-bookface
org: collin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: ${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}

functions:
  get-w23-batch:
    handler: handler.scrapeBookface
    timeout: 90

package:
  patterns:
    - '!node_modules/puppeteer/.local-chromium/**'