S3_AWS_ACCESS_KEY_ID: AKIAV5V4H3GFRTGOCY52
S3_AWS_SECRET_ACCESS_KEY: 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
S3_BUCKET_NAME: performance-audit-files-development
NODE_ENV: local
MOCK_S3_UPLOADS: 'true'
FFMPEG_FILEPATH: null
CACHED_RESPONSES_FILE_IS_LOCAL: 'false'
USE_PLACEHOLDER_BACKGROUND_IMAGES: 'true'