app: finds-tags-in-js-snippet
service: find-tags
org: collin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: ${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}
    TAGSAFE_PROXY_URL: ${file(./config/${opt:stage}.yml):TAGSAFE_PROXY_URL}
    S3_BUCKET_NAME: ${file(./config/${opt:stage}.yml):S3_BUCKET_NAME}
    CDN_HOST: ${file(./config/${opt:stage}.yml):CDN_HOST}

functions:
  estimate-tagsafe-performance-improvements:
    handler: handler.handle
    timeout: 90

package:
  patterns:
    - '!node_modules/puppeteer/.local-chromium/**'