name = "tagsafe-proxier"
main = "src/index.js"
compatibility_date = "2022-12-05"
# node_compat = true

##################
###    DEV    ####
##################
[env.dev]
name = "dev-tagsafe-proxier"

###################
### PRODUCTION ####
###################
[env.production]
name = "tagsafe-proxier"