name = "tagsafe-proxier"
main = "index.js"
compatibility_date = "2022-12-05"
# node_compat = true

##################
###    DEV    ####
##################
[env.dev]
name = "dev-tagsafe-proxier"

[env.dev.vars]
ORIGIN_HOST='www.tagsafe.io'
TAGSAFE_PROXY_HOST='dev-tagsafe-proxier.tagsafe.workers.dev'
SHOULD_PROXY_SCRIPT_SRCS='true'
SHOULD_PROXY_LINK_HREFS='true'
SHOULD_PROXY_IMG_SRCS='true'
SHOULD_INTERCEPT_INJECTED_ELEMENTS='true'


###################
### PRODUCTION ####
###################
[env.production]
name = "tagsafe-proxier"
TAGSAFE_PROXY_HOST='tagsafe-proxier.tagsafe.workers.dev'
SHOULD_PROXY_SCRIPT_SRCS='true'
SHOULD_PROXY_LINK_HREFS='true'
SHOULD_PROXY_IMG_SRCS='true'
SHOULD_INTERCEPT_INJECTED_ELEMENTS='true'


[env.production.vars]
ORIGIN_HOST='www.tagsafe.io'
