app: main-thread-usage
service: main-thread-usage
org: collin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  profile: ${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}

functions:
  calculate-main-thread-usage:
    handler: handler.handle
    timeout: 90
  run-lighthouse-audit:
    handler: lighthouseHandler.handle
    timeout: 90

package:
  patterns:
    - '!node_modules/puppeteer/.local-chromium/**'